### ISSUE TITLE
Square function does not work with negative numbers

### ISSUE THREAD

**Issue by pdominguite** [pdominguite/learning-oss#1]
## Description

The main Python module does not work when we provide negative integers.

### Steps to reproduce

```bash
$ python main.py 6
36

$ python main.py -6
0
```

**Comment by Leone98** [comment]
eu posso lidar com isso

**Comment by pdominguite** [comment]
Cool! Let me know when you're ready :)

**Comment by pdominguite** [comment]
Solved by #3.
